Repository graphql-python/graphene-sqlalchemy, pull requests merged in 2019-03, with the labels that each got.

#172 Consistency table name example with the model name
  README.md
Labels: :book: documentation, bug

#167 Fixed tiny grammatical error in the `tips` page.
  docs/tips.rst
Labels: :book: documentation

#177 Use enum34 backport when Enum is not available
  .travis.yml
  setup.cfg
  setup.py
  tox.ini
Labels: bug

#170 Remove unused import.
  README.md
Labels: :book: documentation, bug
